ALTER SCHEMA ${SCHEMA} OWNER TO ${GROUP};

CREATE TABLE IF NOT EXISTS adv_hello_world.hello_world (
  id bigserial NOT NULL,
  msg varchar(255) NOT NULL
)
WITH(OIDS=FALSE);

ALTER TABLE adv_hello_world.hello_world OWNER TO ${GROUP};
GRANT ALL ON ALL TABLES IN SCHEMA ${SCHEMA} TO ${GROUP};
GRANT ALL ON ALL SEQUENCES IN SCHEMA ${SCHEMA} TO ${GROUP};